#include "lolevel.h"
#include "platform.h"
#include "core.h"

static long *nrflag = (long*)(0x7514+0x8);  // FF18775C & FF1877C8
#define NR_AUTO (0)							// have to explictly reset value back to 0 to enable auto
#define PAUSE_FOR_FILE_COUNTER 100          // Enable delay in capt_seq_hook_raw_here to ensure file counter is updated

#include "../../../generic/capt_seq.c"

//void __attribute__((naked,noinline)) hangdebug() {
//	debug_led(1);
//	while(1);
//}

void __attribute__((naked,noinline)) capt_seq_task() {
// FF882920   IXUS 220: DONE

asm volatile (

	"STMFD SP!, {R3-R9,LR}\n"
	"LDR	R5, =0x3D48C\n"
	"LDR	R7, =0x2E28\n"
	"MOV	R6, #0\n"

"loc_FF882930:\n"
	"LDR	R0, [R7,#4]\n"
	"MOV	R2, #0\n"
	"MOV	R1, SP\n"
	"BL		sub_FF83B5B4\n"
	"TST	R0, #1\n"
	"BEQ	loc_FF88295C\n"
	"LDR	R1, =0x476\n"
	"LDR	R0, =0xFF882448\n"	// aSsshoottask_c at 0xFF882448
	"BL		_DebugAssert\n"
	"BL		_ExitTask\n"
	"LDMFD SP!, {R3-R9,PC}\n"

"loc_FF88295C:\n"
	"LDR	R0, [SP]\n"
	"LDR	R1, [R0]\n"
	"CMP	R1, #0x23\n"
	"ADDCC	PC, PC, R1,LSL#2\n"

"                 B       loc_FF882BA0\n"
"                 B       loc_FF8829FC\n"
"                 B       loc_FF882A14\n"
"                 B       loc_FF882A40\n"
"                 B       loc_FF882A54\n"
"                 B       loc_FF882A4C\n"
"                 B       loc_FF882A60\n"
"                 B       loc_FF882A68\n"
"                 B       loc_FF882A70\n"
"                 B       loc_FF882A8C\n"
"                 B       loc_FF882ACC\n"
"                 B       loc_FF882A98\n"
"                 B       loc_FF882AA4\n"
"                 B       loc_FF882AAC\n"
"                 B       loc_FF882AB4\n"
"                 B       loc_FF882ABC\n"
"                 B       loc_FF882AC4\n"
"                 B       loc_FF882AD4\n"
"                 B       loc_FF882ADC\n"
"                 B       loc_FF882AE4\n"
"                 B       loc_FF882AEC\n"
"                 B       loc_FF882AF4\n"
"                 B       loc_FF882B00\n"
"                 B       loc_FF882B08\n"
"                 B       loc_FF882B10\n"
"                 B       loc_FF882B18\n"
"                 B       loc_FF882B20\n"
"                 B       loc_FF882B2C\n"
"                 B       loc_FF882B34\n"
"                 B       loc_FF882B3C\n"
"                 B       loc_FF882B44\n"
"                 B       loc_FF882B4C\n"
"                 B       loc_FF882B54\n"
"                 B       loc_FF882B5C\n"
"                 B       loc_FF882B68\n"
"                 B       loc_FF882BAC\n"

// jump table entry 0
"loc_FF8829FC:\n"

"		BL	shooting_expo_iso_override\n"  		    // added

"		BL	sub_FF88319C \n"

"		BL	shooting_expo_param_override\n"  		// added

"		BL	sub_FF8800A8 \n"

"		MOV     R0, #0\n"							// added
"		STR     R0, [R5,#0x28]\n"					// added, fixes overrides  behavior at short shutter press (from S95)

//"		LDR	R0, [R5,#0x28] \n"						// above two lines make this code redundant
//"		CMP	R0, #0 \n"								// above two lines make this code redundant
//"		BLNE	sub_FF184F18 \n"					// above two lines make this code redundant

"		B	loc_FF882BAC \n"

// jump table entry 1
"loc_FF882A14: \n"
"		LDR		R8, [R0,#0xC] \n"
"       MOV     R0, R8 \n"

"       BL      sub_FF98B018 \n"

"       BL      capt_seq_hook_raw_here\n"           // added					 

"       MOV     R4, R0 \n"
"       MOV     R2, R8 \n"
"       MOV     R1, #1 \n"
"       BL      sub_FF880A98 \n"
"       TST     R4, #1 \n"
//"       BNE     loc_FF075040 \n"
//"       MOV     R0, R8 \n"
//"       BL      sub_FF1847F0 \n"
	"	MOVEQ	R0, R8 \n"                   	// IXUS 220
	"	BLEQ	sub_FF98AA38 \n"    			// IXUS 220
"       B       loc_FF882BAC \n"

"loc_FF075040: \n"								// IXUS 220 to be checked if not working
"		BL		sub_FF1847C0 \n"				// IXUS 220 to be checked if not working
"		B		loc_FF882BAC \n"				// IXUS 220 to be checked if not working

// jump table entry 2
"loc_FF882A40: \n"
"		MOV	R0, #1 \n"
"		BL	sub_FF88347C \n"
"		B	loc_FF882BAC \n"

// jump table entry 4
"loc_FF882A4C: \n"
"		BL	sub_FF882DD8 \n"
"		B	loc_FF075060 \n"

// jump table entry 3
"loc_FF882A54: \n"
"		BL	sub_FF88317C \n"
"loc_FF075060: \n"
"		STR	R6, [R5,#0x28] \n"
"		B	loc_FF882BAC \n"

// jump table entry 5
"loc_FF882A60: \n"
"		BL	sub_FF883184 \n"
"		B	loc_FF882BAC \n"

// jump table entry 6
"loc_FF882A68: \n"
"		BL	sub_FF883370 \n"
"		B	loc_FF882A90 \n"

// jump table entry 7
"loc_FF882A70: \n"
"		LDR	R4, [R0,#0xC] \n"
"       MOV R0, R4 \n"
"		BL	sub_FF98B1DC \n"
"       MOV R2, R4 \n"
"       MOV R1, #9 \n"
"       BL  sub_FF880A98 \n"
"		B	loc_FF882BAC \n"

// jump table entry 8
"loc_FF882A8C: \n"
"		BL	sub_FF8833E4 \n"
"loc_FF882A90: \n"
"		BL	sub_FF8800A8 \n"
"		B	loc_FF882BAC \n"

// jump table entry 10
"loc_FF882A98: \n"
"		LDR	R0, [R5,#0x58] \n"
"		BL	sub_FF883B70 \n"
"		B	loc_FF882BAC \n"

// jump table entry 11
"loc_FF882AA4: \n"
"		BL	sub_FF883E44 \n"
"		B	loc_FF882BAC \n"

// jump table entry 12
"loc_FF882AAC: \n"
"		BL	sub_FF883EA8 \n"
"		B	loc_FF882BAC \n"

// jump table entry 13
"loc_FF882AB4: \n"
"		BL	sub_FF8840A4 \n"
"		B	loc_FF882BAC \n"

// jump table entry 14
"loc_FF882ABC: \n"
"		BL	sub_FF8844F4 \n"
"		B	loc_FF882BAC \n"

// jump table entry 15
"loc_FF882AC4: \n"
"		BL	sub_FF8845A4 \n"
"		B	loc_FF882BAC \n"

// jump table entry 9
"loc_FF882ACC: \n"
"		BL	sub_FF88317C \n"
"		B	loc_FF882BAC \n"

// jump table entry 16
"loc_FF882AD4: \n"
"		BL	sub_FF989D5C \n"
"		B	loc_FF882BAC \n"

// jump table entry 17
"loc_FF882ADC: \n"
"		BL	sub_FF989F70 \n"
"		B	loc_FF882BAC \n"

// jump table entry 18
"loc_FF882AE4: \n"
"		BL	sub_FF98A014 \n"
"		B	loc_FF882BAC \n"

// jump table entry 19
"loc_FF882AEC: \n"
"		BL	sub_FF98A0E4 \n"
"		B	loc_FF882BAC \n"

// jump table entry 20
"loc_FF882AF4: \n"
"       MOV R0, #0 \n"
"		BL	sub_FF98A354 \n"
"		B	loc_FF882BAC \n"

// jump table entry 21
"loc_FF882B00: \n"
"		BL	sub_FF98A4BC \n"
"		B	loc_FF882BAC \n"

// jump table entry 22
"loc_FF882B08:\n"
"		BL	sub_FF98A554 \n"
"		B	loc_FF882BAC \n"

// jump table entry 23
"loc_FF882B10: \n"
"		BL	sub_FF98A634 \n"
"		B	loc_FF882BAC \n"

// jump table entry 24
"loc_FF882B18: \n"
"		BL	sub_FF883648 \n"
"		B	loc_FF882BAC \n"

// jump table entry 25
"loc_FF882B20: \n"
"		BL	sub_FF883688 \n"
"		BL	sub_FF8391DC \n"
"		B	loc_FF882BAC \n"

// jump table entry 26
"loc_FF882B2C: \n"
"		BL	sub_FF98A1B0 \n"
"		B	loc_FF882BAC \n"

// jump table entry 27
"loc_FF882B34: \n"
"		BL	sub_FF98A218 \n"
"		B	loc_FF882BAC \n"

// jump table entry 28
"loc_FF882B3C: \n"
"		BL	sub_FF8869FC \n"
"		B	loc_FF882BAC \n"

// jump table entry 29
"loc_FF882B44: \n"
"		BL	sub_FF886A80 \n"
"		B	loc_FF882BAC \n"

// jump table entry 30
"loc_FF882B4C: \n"
"		BL	sub_FF98A76C \n"
"		B	loc_FF882BAC \n"

// jump table entry 31
"loc_FF882B54: \n"
"		BL	sub_FF98A7D0 \n"
"		B	loc_FF882BAC \n"

// jump table entry 32
"loc_FF882B5C: \n"
"		BL	sub_FF886ADC \n"
"		BL	sub_FF886A9C \n"
"		B	loc_FF882BAC \n"

// jump table entry 33
"loc_FF882B68: \n"
"		MOV	R0, #1 \n"
"		BL	sub_FF98B9D0 \n"
"		MOV	R0, #1 \n"
"		BL	sub_FF98BB04 \n"
"		LDRH	R0, [R5,#0x98] \n"
"		CMP	R0, #4 \n"
"		LDRNEH	R0, [R5] \n"
"		SUBNE	R1, R0, #0x8200 \n"
"		SUBNES	R1, R1, #0x2A \n"
"		BNE	loc_FF882BAC \n"
"		BL	sub_FF886A80 \n"
"		BL	sub_FF8870A8 \n"
"		BL	sub_FF886F00 \n"
"		B	loc_FF882BAC \n"

// jump table default entry
"loc_FF882BA0: \n"
"		LDR	R1, =0x5D7 \n"
"		LDR	R0, =0xFF882448 \n"	// aSsshoottask_c
"		BL	_DebugAssert \n"

// jump table entry 34
"loc_FF882BAC: \n"
"		LDR	R0, [SP] \n"
"		LDR	R1, [R0,#4] \n"
"		LDR	R0, [R7] \n"
"		BL	sub_FF88DBD8 \n"
"		LDR	R4, [SP] \n"
"		LDR	R0, [R4,#8] \n"
"		CMP	R0, #0 \n"
"		LDREQ	R0, =0xFF882448 \n"	// aSsshoottask_c
"		MOVEQ	R1, #0x118 \n"
"		BLEQ	_DebugAssert \n"
"		STR	R6, [R4,#8] \n"
"		B	loc_FF882930 \n"
	);
}

/*************************************************************/

void __attribute__((naked,noinline)) exp_drv_task(){
// FF8CBCBC   IXUS220: DONE
 asm volatile(
"               STMFD   SP!, {R4-R9,LR} \n"
"               SUB     SP, SP, #0x24 \n"
"               LDR     R6, =0x4238 \n"
"               LDR     R7, =0xBB8 \n"
"               LDR     R4, =0x58A54 \n"
"               MOV     R0, #0 \n"
"               ADD     R5, SP, #0x14 \n"
"               STR     R0, [SP,#0x10] \n"
"loc_FF8CBCDC: \n"
"               LDR     R0, [R6,#0x20] \n"
"               MOV     R2, #0 \n"
"               ADD     R1, SP, #0x20 \n"
"               BL      sub_FF83B5B4 \n"
"               LDR     R0, [SP,#0x10] \n"
"               CMP     R0, #1 \n"
"               BNE     loc_FF8CBD28 \n"
"               LDR     R0, [SP,#0x20] \n"
"               LDR     R0, [R0] \n"
"               CMP     R0, #0x14 \n"
"               CMPNE   R0, #0x15 \n"
"               CMPNE   R0, #0x16 \n"
"               CMPNE   R0, #0x17 \n"
"               BEQ     loc_FF8CBE88 \n"
"               CMP     R0, #0x29 \n"
"               BEQ     loc_FF8CBE10 \n"
"               ADD     R1, SP, #0x10 \n"
"               MOV     R0, #0 \n"
"               BL      sub_FF8CBC6C \n"
"loc_FF8CBD28: \n"
"               LDR     R0, [SP,#0x20] \n"
"               LDR     R1, [R0] \n"
"               CMP     R1, #0x2F \n"
"               BNE     loc_FF8CBD54 \n"
"               BL      sub_FF8CD0F8 \n"
"               LDR     R0, [R6,#0x1C] \n"
"               MOV     R1, #1 \n"
"               BL      sub_FF88DBD8 \n"
"               BL      _ExitTask \n"
"               ADD     SP, SP, #0x24 \n"
"               LDMFD   SP!, {R4-R9,PC} \n"
"loc_FF8CBD54: \n"
"               CMP     R1, #0x2E \n"
"               BNE     loc_FF8CBD70 \n"
"               LDR     R2, [R0,#0x8C]! \n"
"               LDR     R1, [R0,#4] \n"
"               MOV     R0, R1 \n"
"               BLX     R2 \n"
"               B       loc_FF8CC318 \n"
"loc_FF8CBD70: \n"
"               CMP     R1, #0x27 \n"
"               BNE     loc_FF8CBDC0 \n"
"               LDR     R0, [R6,#0x1C] \n"
"               MOV     R1, #0x80 \n"
"               BL      sub_FF88DC0C \n"
"               LDR     R0, =0xFF8C6E20 \n" // IXUS 220 sub_0xFF8C6E20
"               MOV     R1, #0x80 \n"
"               BL      sub_FF97C814 \n"
"               LDR     R0, [R6,#0x1C] \n"
"               MOV     R2, R7 \n"
"               MOV     R1, #0x80 \n"
"               BL      sub_FF88DB18 \n"
"               TST     R0, #1 \n"
"               LDRNE   R1, =0x174F \n"
"               BNE     loc_FF8CBE7C \n"
"loc_FF8CBDAC: \n"
"               LDR     R1, [SP,#0x20] \n"
"               LDR     R0, [R1,#0x90] \n"
"               LDR     R1, [R1,#0x8C] \n"
"               BLX     R1 \n"
"               B       loc_FF8CC318 \n"
"loc_FF8CBDC0: \n"
"               CMP     R1, #0x28 \n"
"               BNE     loc_FF8CBE08 \n"
"               ADD     R1, SP, #0x10 \n"
"               BL      sub_FF8CBC6C \n"
"               LDR     R0, [R6,#0x1C] \n"
"               MOV     R1, #0x100 \n"
"               BL      sub_FF88DC0C \n"
"               LDR     R0, =0xFF8C6E30 \n" // IXUS220 sub_0xFF8C6E30
"               MOV     R1, #0x100 \n"
"               BL      sub_FF97CACC \n"
"               LDR     R0, [R6,#0x1C] \n"
"               MOV     R2, R7 \n"
"               MOV     R1, #0x100 \n"
"               BL      sub_FF88DB18 \n"
"               TST     R0, #1 \n"
"               BEQ     loc_FF8CBDAC \n"
"               LDR     R1, =0x1759 \n"
"               B       loc_FF8CBE7C \n"
"loc_FF8CBE08: \n"
"               CMP     R1, #0x29 \n"
"               BNE     loc_FF8CBE20 \n"
"loc_FF8CBE10: \n"
"               LDR     R0, [SP,#0x20] \n"
"               ADD     R1, SP, #0x10 \n"
"               BL      sub_FF8CBC6C \n"
"               B       loc_FF8CBDAC \n"
"loc_FF8CBE20: \n"
"               CMP     R1, #0x2C \n"
"               BNE     loc_FF8CBE38 \n"
"               BL      sub_FF8B8760 \n"
"               BL      sub_FF8B93D0 \n"
"               BL      sub_FF8B8F48 \n"
"               B       loc_FF8CBDAC \n"
"loc_FF8CBE38: \n"
"               CMP     R1, #0x2D \n"
"               BNE     loc_FF8CBE88 \n"
"               LDR     R0, [R6,#0x1C] \n"
"               MOV     R1, #4 \n"
"               BL      sub_FF88DC0C \n"
"               LDR     R1, =0xFF8C6E50 \n" // IXUS220 sub_FF8C6E50
"               LDR     R0, =0xFFFFF400 \n"
"               MOV     R2, #4 \n"
"               BL      sub_FF8B81D4 \n"
"               BL      sub_FF8B8464 \n"
"               LDR     R0, [R6,#0x1C] \n"
"               MOV     R2, R7 \n"
"               MOV     R1, #4 \n"
"               BL      sub_FF88DA34 \n"
"               TST     R0, #1 \n"
"               BEQ     loc_FF8CBDAC \n"
"               LDR     R1, =0x1781 \n"
"loc_FF8CBE7C: \n"
"               LDR     R0, =0xFF8C75F4 \n" //"ExpDrv.c"
"               BL      _DebugAssert \n"
"               B       loc_FF8CBDAC \n"
"loc_FF8CBE88: \n"
"               LDR     R0, [SP,#0x20] \n"
"               MOV     R8, #1 \n"
"               LDR     R1, [R0] \n"
"               CMP     R1, #0x12 \n"
"               CMPNE   R1, #0x13 \n"
"               BNE     loc_FF8CBEF0 \n"
"               LDR     R1, [R0,#0x7C] \n"
"               ADD     R1, R1, R1,LSL#1 \n"
"               ADD     R1, R0, R1,LSL#2 \n"
"               SUB     R1, R1, #8 \n"
"               LDMIA   R1, {R2,R3,R9} \n"
"               STMIA   R5, {R2,R3,R9} \n"
"               BL      sub_FF8C9F20 \n"
"               LDR     R0, [SP,#0x20] \n"
"               LDR     R1, [R0,#0x7C] \n"
"               LDR     R3, [R0,#0x8C] \n"
"               LDR     R2, [R0,#0x90] \n"
"               ADD     R0, R0, #4 \n"
"               BLX     R3 \n"
"               LDR     R0, [SP,#0x20] \n"
"               BL      sub_FF8CD504 \n"
"               LDR     R0, [SP,#0x20] \n"
"               LDR     R1, [R0,#0x7C] \n"
"               LDR     R2, [R0,#0x98] \n"
"               LDR     R3, [R0,#0x94] \n"
"               B       loc_FF8CC204 \n"
"loc_FF8CBEF0: \n"
"               CMP     R1, #0x14 \n"
"               CMPNE   R1, #0x15 \n"
"               CMPNE   R1, #0x16 \n"
"               CMPNE   R1, #0x17 \n"
"               BNE     loc_FF8CBFA8 \n"
"               ADD     R3, SP, #0x10 \n"
"               ADD     R2, SP, #0x4 \n"
"               ADD     R1, SP, #0x14 \n"
"               BL      sub_FF8CA188 \n"
"               CMP     R0, #1 \n"
"               MOV     R9, R0 \n"
"               CMPNE   R9, #5 \n"
"               BNE     loc_FF8CBF44 \n"
"               LDR     R0, [SP,#0x20] \n"
"               MOV     R2, R9 \n"
"               LDR     R1, [R0,#0x7C]! \n"
"               LDR     R12, [R0,#0x10]! \n"
"               LDR     R3, [R0,#4] \n"
"               ADD     R0, SP, #0x4 \n"
"               BLX     R12 \n"
"               B       loc_FF8CBF7C \n"
"loc_FF8CBF44: \n"
"               LDR     R0, [SP,#0x20] \n"
"               CMP     R9, #2 \n"
"               LDR     R3, [R0,#0x90] \n"
"               CMPNE   R9, #6 \n"
"               BNE     loc_FF8CBF90 \n"
"               LDR     R12, [R0,#0x8C] \n"
"               MOV     R2, R9 \n"
"               MOV     R1, #1 \n"
"               ADD     R0, SP, #0x4 \n"
"               BLX     R12 \n"
"               LDR     R0, [SP,#0x20] \n"
"               ADD     R2, SP, #0x4 \n"
"               ADD     R1, SP, #0x14 \n"
"               BL      sub_FF8CB95C \n"
"loc_FF8CBF7C: \n"
"               LDR     R0, [SP,#0x20] \n"
"               LDR     R2, [SP,#0x10] \n"
"               MOV     R1, R9 \n"
"               BL      sub_FF8CBC0C \n"
"               B       loc_FF8CC20C \n"
"loc_FF8CBF90: \n"
"               LDR     R1, [R0,#0x7C] \n"
"               LDR     R12, [R0,#0x8C] \n"
"               MOV     R2, R9 \n"
"               ADD     R0, R0, #4 \n"
"               BLX     R12 \n"
"               B       loc_FF8CC20C \n"
"loc_FF8CBFA8: \n"
"               CMP     R1, #0x23 \n"
"               CMPNE   R1, #0x24 \n"
"               BNE     loc_FF8CBFF4 \n"
"               LDR     R1, [R0,#0x7C] \n"
"               ADD     R1, R1, R1,LSL#1 \n"
"               ADD     R1, R0, R1,LSL#2 \n"
"               SUB     R1, R1, #8 \n"
"               LDMIA   R1, {R2,R3,R9} \n"
"               STMIA   R5, {R2,R3,R9} \n"
"               BL      sub_FF8C8D28 \n"
"               LDR     R0, [SP,#0x20] \n"
"               LDR     R1, [R0,#0x7C] \n"
"               LDR     R3, [R0,#0x8C] \n"
"               LDR     R2, [R0,#0x90] \n"
"               ADD     R0, R0, #4 \n"
"               BLX     R3 \n"
"               LDR     R0, [SP,#0x20] \n"
"               BL      sub_FF8C91FC \n"
"               B       loc_FF8CC20C \n"
"loc_FF8CBFF4: \n"
"               ADD     R1, R0, #4 \n"
"               LDMIA   R1, {R2,R3,R9} \n"
"               STMIA   R5, {R2,R3,R9} \n"
"               LDR     R1, [R0] \n"
"               CMP     R1, #0x27 \n"
"               ADDCC   PC, PC, R1,LSL#2 \n"
"               B       loc_FF8CC1F4 \n"
"               B       loc_FF8CC0AC \n"
"               B       loc_FF8CC0AC \n"
"               B       loc_FF8CC0B4 \n"
"               B       loc_FF8CC0BC \n"
"               B       loc_FF8CC0BC \n"
"               B       loc_FF8CC0BC \n"
"               B       loc_FF8CC0AC \n"
"               B       loc_FF8CC0B4 \n"
"               B       loc_FF8CC0BC \n"
"               B       loc_FF8CC0BC \n"
"               B       loc_FF8CC0D4 \n"
"               B       loc_FF8CC0D4 \n"
"               B       loc_FF8CC1E0 \n"
"               B       loc_FF8CC1E8 \n"
"               B       loc_FF8CC1E8 \n"
"               B       loc_FF8CC1E8 \n"
"               B       loc_FF8CC1E8 \n"
"               B       loc_FF8CC1F0 \n"
"               B       loc_FF8CC1F4 \n"
"               B       loc_FF8CC1F4 \n"
"               B       loc_FF8CC1F4 \n"
"               B       loc_FF8CC1F4 \n"
"               B       loc_FF8CC1F4 \n"
"               B       loc_FF8CC1F4 \n"
"               B       loc_FF8CC0C4 \n"
"               B       loc_FF8CC0CC \n"
"               B       loc_FF8CC0CC \n"
"               B       loc_FF8CC0E0 \n"
"               B       loc_FF8CC0E0 \n"
"               B       loc_FF8CC0E8 \n"
"               B       loc_FF8CC120 \n"
"               B       loc_FF8CC158 \n"
"               B       loc_FF8CC190 \n"
"               B       loc_FF8CC1C8 \n"
"               B       loc_FF8CC1C8 \n"
"               B       loc_FF8CC1F4 \n"
"               B       loc_FF8CC1F4 \n"
"               B       loc_FF8CC1D0 \n"
"               B       loc_FF8CC1D8 \n"
"loc_FF8CC0AC: \n"
// jumptable FF0BE064 entries 0,1,6
"               BL      sub_FF8C7424 \n"
"               B       loc_FF8CC1F4 \n"
"loc_FF8CC0B4: \n"
// jumptable FF0BE064 entries 2,7
"               BL      sub_FF8C7720 \n"
"               B       loc_FF8CC1F4 \n"
"loc_FF8CC0BC: \n"
// jumptable FF0BE064 entries 3-5,8,9
"               BL      sub_FF8C7988 \n"
"               B       loc_FF8CC1F4 \n"
"loc_FF8CC0C4: \n"
// jumptable FF0BE064 entry 24
"               BL      sub_FF8C7C3C \n"
"               B       loc_FF8CC1F4 \n"
"loc_FF8CC0CC: \n"
// jumptable FF0BE064 entries 25,26
"               BL      sub_FF8C7E54 \n"
"               B       loc_FF8CC1F4 \n"
"loc_FF8CC0D4: \n"
// jumptable FF0BE064 entries 10,11
//"               BL      sub_FF8C8310 \n"
"               BL      sub_FF8C8310_my \n"     // patched
"               MOV     R8, #0 \n"
"               B       loc_FF8CC1F4 \n"
"loc_FF8CC0E0: \n"
// jumptable FF0BE064 entries 27,28
"               BL      sub_FF8C84DC \n"
"               B       loc_FF8CC1F4 \n"
"loc_FF8CC0E8: \n"
// jumptable FF0BE064 entry 29
"               LDRH    R1, [R0,#4] \n"
"               STRH    R1, [SP,#0x14] \n"
"               LDRH    R1, [R4,#2] \n"
"               STRH    R1, [SP,#0x16] \n"
"               LDRH    R1, [R4,#4] \n"
"               STRH    R1, [SP,#0x18] \n"
"               LDRH    R1, [R4,#6] \n"
"               STRH    R1, [SP,#0x1A] \n"
"               LDRH    R1, [R0,#0xC] \n"
"               STRH    R1, [SP,#0x1C] \n"
"               LDRH    R1, [R4,#0xA] \n"
"               STRH    R1, [SP,#0x1E] \n"
"               BL      sub_FF8CD18C \n"
"               B       loc_FF8CC1F4 \n"
"loc_FF8CC120: \n"
//; jumptable FF0BE064 entry 30
"               LDRH    R1, [R0,#4] \n"
"               STRH    R1, [SP,#0x14] \n"
"               LDRH    R1, [R4,#2] \n"
"               STRH    R1, [SP,#0x16] \n"
"               LDRH    R1, [R4,#4] \n"
"               STRH    R1, [SP,#0x18] \n"
"               LDRH    R1, [R4,#6] \n"
"               STRH    R1, [SP,#0x1A] \n"
"               LDRH    R1, [R4,#8] \n"
"               STRH    R1, [SP,#0x1C] \n"
"               LDRH    R1, [R4,#0xA] \n"
"               STRH    R1, [SP,#0x1E] \n"
"               BL      sub_FF8CD304 \n"
"               B       loc_FF8CC1F4 \n"
"loc_FF8CC158: \n"
//; jumptable FF0BE064 entry 31
"               LDRH    R1, [R4] \n"
"               STRH    R1, [SP,#0x14] \n"
"               LDRH    R1, [R0,#6] \n"
"               STRH    R1, [SP,#0x16] \n"
"               LDRH    R1, [R4,#4] \n"
"               STRH    R1, [SP,#0x18] \n"
"               LDRH    R1, [R4,#6] \n"
"               STRH    R1, [SP,#0x1A] \n"
"               LDRH    R1, [R4,#8] \n"
"               STRH    R1, [SP,#0x1C] \n"
"               LDRH    R1, [R4,#0xA] \n"
"               STRH    R1, [SP,#0x1E] \n"
"               BL      sub_FF8CD3B8 \n"
"               B       loc_FF8CC1F4 \n"
"loc_FF8CC190: \n"
//; jumptable FF0BE064 entry 32
"               LDRH    R1, [R4] \n"
"               STRH    R1, [SP,#0x14] \n"
"               LDRH    R1, [R4,#2] \n"
"               STRH    R1, [SP,#0x16] \n"
"               LDRH    R1, [R4,#4] \n"
"               STRH    R1, [SP,#0x18] \n"
"               LDRH    R1, [R4,#6] \n"
"               STRH    R1, [SP,#0x1A] \n"
"               LDRH    R1, [R0,#0xC] \n"
"               STRH    R1, [SP,#0x1C] \n"
"               LDRH    R1, [R4,#0xA] \n"
"               STRH    R1, [SP,#0x1E] \n"
"               BL      sub_FF8CD460 \n"
"               B       loc_FF8CC1F4 \n"
"loc_FF8CC1C8: \n"
//; jumptable FF0BE064 entries 33,34
"               BL      sub_FF8C8B1C \n"
"               B       loc_FF8CC1F4 \n"
"loc_FF8CC1D0: \n"
//; jumptable FF0BE064 entry 37
"               BL      sub_FF8C9300 \n"
"               B       loc_FF8CC1F4 \n"
"loc_FF8CC1D8: \n"
//; jumptable FF0BE064 entry 38
"               BL      sub_FF8C980C \n"
"               B       loc_FF8CC1F4 \n"
"loc_FF8CC1E0: \n"
//; jumptable FF0BE064 entry 12
"               BL      sub_FF8C99EC \n"
"               B       loc_FF8CC1F4 \n"
"loc_FF8CC1E8: \n"
//; jumptable FF0BE064 entries 13-16
"               BL      sub_FF8C9BA8 \n"
"               B       loc_FF8CC1F4 \n"
"loc_FF8CC1F0: \n"
//; jumptable FF0BE064 entry 17
"               BL      sub_FF8C9D18 \n"
"loc_FF8CC1F4: \n"
//; jumptable FF0BE064 default entry
//; jumptable FF0BE064 entries 18-23,35,36
"               LDR     R0, [SP,#0x20] \n"
"               LDR     R1, [R0,#0x7C] \n"
"               LDR     R2, [R0,#0x90] \n"
"               LDR     R3, [R0,#0x8C] \n"
"loc_FF8CC204: \n"
"               ADD     R0, R0, #4 \n"
"               BLX     R3 \n"
"loc_FF8CC20C: \n"
"               LDR     R1, [SP,#0x20] \n"
"               LDR     R0, [R1] \n"
"               CMP     R0, #0x10 \n"
"               BEQ     loc_FF8CC244 \n"
"               BGT     loc_FF8CC234 \n"
"               CMP     R0, #1 \n"
"               CMPNE   R0, #4 \n"
"               CMPNE   R0, #0xE \n"
"               BNE     loc_FF8CC254 \n"
"               B       loc_FF8CC244 \n"
"loc_FF8CC234: \n"
"               CMP     R0, #0x13 \n"
"               CMPNE   R0, #0x17 \n"
"               CMPNE   R0, #0x1A \n"
"               BNE     loc_FF8CC254 \n"
"loc_FF8CC244: \n"
"               LDRH    R0, [R4] \n"
"               STRH    R0, [SP,#0x14] \n"
"               LDRH    R0, [R4,#8] \n"
"               STRH    R0, [SP,#0x1C] \n"
"loc_FF8CC254: \n"
"               CMP     R8, #1 \n"
"               BNE     loc_FF8CC2A0 \n"
"               LDR     R0, [R1,#0x7C] \n"
"               MOV     R2, #0xC \n"
"               ADD     R0, R0, R0,LSL#1 \n"
"               ADD     R0, R1, R0,LSL#2 \n"
"               SUB     R8, R0, #8 \n"
"               LDR     R0, =0x58A54 \n"
"               ADD     R1, SP, #0x14 \n"
"               BL      sub_FFB9C3C0 \n"
"               LDR     R0, =0x58A60 \n"
"               MOV     R2, #0xC \n"
"               ADD     R1, SP, #0x14 \n"
"               BL      sub_FFB9C3C0 \n"
"               LDR     R0, =0x58A6C \n"
"               MOV     R2, #0xC \n"
"               MOV     R1, R8 \n"
"               BL      sub_FFB9C3C0 \n"
"               B       loc_FF8CC318 \n"
"loc_FF8CC2A0: \n"
"               LDR     R0, [R1] \n"
"               MOV     R3, #1 \n"
"               CMP     R0, #0xB \n"
"               BNE     loc_FF8CC2E4 \n"
"               MOV     R2, #0 \n"
"               STRD    R2, [SP] \n"
"               MOV     R2, R3 \n"
"               MOV     R1, R3 \n"
"               MOV     R0, #0 \n"
"               BL      sub_FF8C7204 \n"
"               MOV     R3, #1 \n"
"               MOV     R2, #0 \n"
"               STRD    R2, [SP] \n"
"               MOV     R2, R3 \n"
"               MOV     R1, R3 \n"
"               MOV     R0, #0 \n"
"               B       loc_FF8CC314 \n"
"loc_FF8CC2E4: \n"
"               MOV     R2, #1 \n"
"               STRD    R2, [SP] \n"
"               MOV     R3, R2 \n"
"               MOV     R1, R2 \n"
"               MOV     R0, R2 \n"
"               BL      sub_FF8C7204 \n"
"               MOV     R3, #1 \n"
"               MOV     R2, R3 \n"
"               MOV     R1, R3 \n"
"               MOV     R0, R3 \n"
"               STR     R3, [SP] \n"
"               STR     R3, [SP,#0x4] \n"
"loc_FF8CC314: \n"
"               BL      sub_FF8C7370 \n"
"loc_FF8CC318: \n"
"               LDR     R0, [SP,#0x20] \n"
"               BL      sub_FF8CD0F8 \n"
"               B       loc_FF8CBCDC \n"
 );
}

void __attribute__((naked,noinline)) sub_FF8C8310_my() {
//FF8C8310      IXUS220: DONE
	asm volatile (
"                STMFD   SP!, {R4-R8,LR} \n"
"                LDR     R7, =0x4238 \n"
"                MOV     R4, R0 \n"
"                LDR     R0, [R7,#0x1C] \n"
"                MOV     R1, #0x3E \n"
"                BL      sub_FF88DC0C \n"
"                MOV     R2, #0 \n"
"                LDRSH   R0, [R4,#4] \n"
"                MOV     R1, R2 \n"
"                BL      sub_FF8C6EB0 \n"
"                MOV     R5, R0 \n"
"                LDRSH   R0, [R4,#6] \n"
"                BL      sub_FF8C7000 \n"
"                LDRSH   R0, [R4,#8] \n"
"                BL      sub_FF8C7058 \n"
"                LDRSH   R0, [R4,#0xA] \n"
"                BL      sub_FF8C70B0 \n"
"                LDRSH   R0, [R4,#0xC] \n"
"                MOV     R1, #0 \n"
"                BL      sub_FF8C7108 \n"
"                MOV     R6, R0 \n"
"                LDRSH   R0, [R4,#0xE] \n"
"                BL      sub_FF8CD128 \n"
"                LDR     R0, [R4] \n"
"                LDR     R8, =0x58A6C \n"
"                CMP     R0, #0xB \n"
"                MOVEQ   R5, #0 \n"
"                MOVEQ   R6, R5 \n"
"                BEQ     loc_FF8C83AC \n"
"                CMP     R5, #1 \n"
"                BNE     loc_FF8C83AC \n"
"                LDRSH   R0, [R4,#4] \n"
"                LDR     R1, =0xFF8C6E10 \n"    // IXUS220 sub_FF8C6E10
"                MOV     R2, #2 \n"
"                BL      sub_FF97C968 \n"
"                STRH    R0, [R4,#4] \n"
"                MOV     R0, #0 \n"
"                STR     R0, [R7,#0x28] \n"
"                B       loc_FF8C83B4 \n"

"loc_FF8C83AC: \n"
"                LDRH    R0, [R8] \n"
"                STRH    R0, [R4,#4] \n"

"loc_FF8C83B4: \n"
"                CMP     R6, #1 \n"
"                LDRNEH  R0, [R8,#8] \n"
"                BNE     loc_FF8C83D0 \n"
"                LDRSH   R0, [R4,#0xC] \n"
"                LDR     R1, =0xFF8C6E94 \n"    // sub_FF8C6E94
"                MOV     R2, #0x20 \n"
"                BL      sub_FF8CD148 \n"

"loc_FF8C83D0: \n"
"                STRH    R0, [R4,#0xC] \n"
"                LDRSH   R0, [R4,#6] \n"
//"                BL      sub_FF8B84D0 \n"
"                BL      sub_FF8B84D0_my \n"    // patched
"				 B		 sub_FF8C83DC \n"	    // continue in firmware
	);
}

void __attribute__((naked,noinline)) sub_FF8B84D0_my() {
//FF8B84D0     IXUS220: DONE
	asm volatile (
"                STMFD   SP!, {R4-R6,LR} \n"
"                LDR     R5, =0x3EE0 \n"
"                MOV     R4, R0 \n"
"                LDR     R0, [R5,#4] \n"
"                CMP     R0, #1 \n"
"                LDRNE   R1, =0x146 \n"
"                LDRNE   R0, =0xFF8B8308 \n" //aShutter_c IXUS220 at FF8B8308
"                BLNE    _DebugAssert \n"
"                CMN     R4, #0xC00 \n"
"                LDREQSH R4, [R5,#2] \n"
"                CMN     R4, #0xC00 \n"
"                MOVEQ   R1, #0x14C \n"
"                LDRNE   R0, =0xFF8B8308 \n" //aShutter_c IXUS220 at FF8B8308
"                STRH    R4, [R5,#2] \n"
"                BLEQ    _DebugAssert \n"
"                MOV     R0, R4 \n"
"                BL      apex2us \n"	    // patched
"				 B		 sub_FF8B8514 \n"	// IXUS220 continue in firmware at ff8b8510 ???
);
}
